CREATE TABLE public.salesinfo (
	CREATEid serial NOT NULL,
	CREATE序号 varchar(10) NULL,
	CREATE品牌 varchar(10) NULL,
	CREATE标记类型 varchar(20) NULL,
	CREATE区域 varchar(10) NULL,
	CREATE省份 varchar(100) NULL,
	CREATE城市 varchar(40) NULL,
	CREATE小区 varchar(20) NULL,
	CREATE区县 varchar(40) NULL,
	CREATE邮编 varchar(8) NULL,
	CREATE城市级别 varchar(4) NULL,
	CREATE网点类型 varchar(8) NULL,
	CREATE项目状态 varchar(8) NULL,
	CREATE辖区代码 varchar(10) NULL,
	CREATE经销商代码 varchar(40) NULL,
	CREATE名称 varchar(100) NULL,
	CREATE简称 varchar(40) NULL,
	CREATE地址 text NULL,
	CREATE经度 numeric NULL,
	CREATE纬度 numeric NULL,
	CREATE标签 text NULL,
	CREATE投资人集团 varchar(100) NULL,
	CREATE年份 varchar(10) NULL,
	CREATE月份 varchar(8) NULL,
	CREATE控股投资人 varchar(100) NULL,
	CREATE其他投资人 varchar(200) NULL,
	CREATE备注 text NULL,
	CREATE电话 varchar(15) NULL,
	CREATE网点级别 varchar(40) NULL,
	CREATE工位数量 numeric NULL,
	CREATE乘用车 bool NULL DEFAULT false,
	CREATE商务车 bool NULL DEFAULT false,
	CREATE金融服务 bool NULL DEFAULT false,
	CREATE服务中心 bool NULL DEFAULT false,
	CREATE特殊车型授权 bool NULL DEFAULT false,
	CREATE充电桩 bool NULL DEFAULT false,
	CREATE大客户服务 bool NULL DEFAULT false,
	CREATE认证二手车 bool NULL DEFAULT false,
	CREATE"She'sMercedes" bool NULL DEFAULT false,
	CREATECONSTRAINT salesinfo_pkey PRIMARY KEY (id)
);
